### ISSUE TITLE
[Suggestion] Increase page width

### ISSUE THREAD

**Issue by chinmaydd** [radareorg/blog#26]
Can we increase the width available for text on the page? It seems we are wasting a lot of it on whitespace.

Rendered:
![r2blog](https://user-images.githubusercontent.com/6960646/29274880-ed8ca55e-8126-11e7-8b67-9791fa70d3b4.png)

**Comment by sivaramaaa** [comment]
+1 for this idea

**Comment by XVilka** [comment]
Fixed.
